### ISSUE TITLE
Issue 1: User can check weather for each day of the week

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can check the weather for a specific day of the week

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a "check the weather" link for each day of the current week that will show a modal containing weather information for that specific day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="409" alt="feature-1-mobile" src="https://user-images.githubusercontent.com/103399595/190872217-785c756e-3b3c-4f94-bef6-3b10753a69cb.png">

<img width="893" alt="feature-1-desktop" src="https://user-images.githubusercontent.com/103399595/190872219-0a135859-4ffa-4de5-899a-d0b75a5dd461.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include script from DB designer

### ⚡ Client Tasks

- [x] link googlefonts, bootstrap, fontawesome to index.html
- [x] Create a component to generate day "cards" for each day of the week
- [x] make sure cards are styled properly for mobile and css (media queries)
- [x] get current date to update day cards to show the corresponding dates (monday -> corresponding date, etc.) 
- [x] add a "check the weather" link to each day card
- [x] use geolocation api to obtain user's location (to use for fetch request)
- [x] add event listener to each anchor tag to send a fetch request to the weather api for weather from that day
- [x] create modal that will show weather information from api
- [x] add event listener to close modal

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
