### ISSUE TITLE
Issue 2: User can write journal logs on days they went surfing

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can write about how surfing was for the days they went surfing.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can check a checkbox if they went surfing that day.
Checking the box will change the color of the header for that day to indicate that user went surfing as well as show a "add a log" link.
User can click "add a log" link which will show a modal where the user can write and save their log.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="305" alt="feature-2-mobile-1" src="https://user-images.githubusercontent.com/103399595/191578819-f2d40ffc-cd0f-47a4-bdd5-10c63019f24e.png">
<img width="457" alt="feature-2-mobile-2" src="https://user-images.githubusercontent.com/103399595/191578823-81b064c3-d487-44b5-a47c-a7bd218cc1c0.png">

<img width="815" alt="feature-2-desktop-1" src="https://user-images.githubusercontent.com/103399595/191578842-15603faa-8bde-4917-a9e8-8c32cd510be8.png">
<img width="840" alt="feature-2-desktop-2" src="https://user-images.githubusercontent.com/103399595/191578856-de75153f-88e2-404d-a636-e17e14763350.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] update entries table to include a "date" column

### ☁️ Server Tasks

- [x] create 'POST' route to receive user's log entry and store/insert in "entries" table of db
- [x] return 'content' column from "entries' table back to client

### ⚡ Client Tasks

- [x] Update "home" component to include checkbox on each 'day' card
- [x] add onChange event handler to change state of each checkbox(true/false) when it is clicked or unclicked
- [x] change color of card header and show "add a log" link if checkbox is clicked (when clicked state is true)
- [x] make sure header color changes back to default and "add a log" link is hidden if checkbox is unchecked
- [x] create modal to show when user clicks "add a log" link
- [x] add textarea and submit button on modal where user can write log entries
- [x] add event handler to close modal when x mark button is clicked, but not save entry to db (not send post req to server)
- [x] send POST req to server when submit button is clicked (create onSubmit event handler)
- [x]  show entry on "day card" after submit button is clicked (from response from server)

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
