### ISSUE TITLE
Issue 6: User can view past entries/logs

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can look at all past log entires they wrote

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "Logs" tab to be taken to a new page that contains all previous logs 
(logs tab is on nav bar for desktop view and menu dropdown, in menu dropdown only for mobile view)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="584" alt="feature-6-mobile" src="https://user-images.githubusercontent.com/103399595/192038370-9fb7ff3a-1e52-4211-aeba-3b4b470e9a47.png">
<img width="849" alt="feature-6-desktop" src="https://user-images.githubusercontent.com/103399595/192038393-a1de3114-b358-4b64-aae9-64fa55226ad9.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a "GET" route to obtain all entries in entries table 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create 'Navbar' component and add to return expression of app.jsx
- [x] make nav bar that has app name and menu icon
- [x] create app drawer to show when menu icon is clicked 
- [x]  include links to "home" and "past logs" view on menu dropdown 
- [x] create onClick event handler to open/close app drawer when menu icon is clicked
- [x] add onClick event handler to app drawer background to close drawer when user clicks anywhere on the background
- [x] add slide in animation to app drawer for smoother transition
- [x] add "logs" link to navbar only for desktop view
- [x] Create a component for the 'past logs' view
- [x] add fetch request to "get" all entries in the entries table 
- [x] show results from fetch request onto 'past logs' page with proper styling for mobile and desktop
- [x] add onClick event handler to show weather when user clicks 'the weather' link
- [x] use hashrouting to switch from home and past logs page by clicking on links on menu dropdown and navbar links

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
